### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by joselimajr** [zehengl/ezapi-tmdb#2]
Is there a way to select language for the returned information?

The API allows it: https://developers.themoviedb.org/3/getting-started/languages

Suggestion: In file ...tmdb\three\__init__.py

class TMDb(*mixins):
    def __init__(self, api_key, language):
        self.api_key = api_key
        self.language = language
        self.session = requests.Session()
        self.session.headers.update({"Content-Type": "application/json;charset=utf-8"})

    def make_request(self, method, url, params, payload=None):
        params.update({"api_key": self.api_key})
        params.update({"language": self.language})
        return self.session.request(method, url, params=params, json=payload)

**Comment by zehengl** [comment]
@joselimajr Thanks for the idea. A pull request is welcome! 😄

**Comment by zehengl** [comment]
@all-contributors please add @joselimajr for ideas
